[package]
name = "pdf-to-image"
version = "0.0.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
image = "0.23.12"
resvg = "0.13.0"
tiny-skia = "0.3.0"
usvg = "0.13"
